### ISSUE TITLE
Querying with wrong block hash or transaction hash throws exception, it should return empty row

### ISSUE THREAD

**Issue by ayushvasu** [Impetus/eth-jdbc-connector#22]
When querying with transaction or block, which does not exists, it throws exception. ideally it should return empty result set instead of throwing exception.

Exception comes as below.

`Exception in thread "main" java.lang.NullPointerException
	at com.impetus.eth.parser.EthQueryExecutor.getDataNode(EthQueryExecutor.java:291)
	at com.impetus.blkch.sql.parser.AbstractQueryExecutor.executeDirectAPIs(AbstractQueryExecutor.java:55)
	at com.impetus.blkch.sql.parser.AbstractQueryExecutor.executeDirectAPIs(AbstractQueryExecutor.java:46)
	at com.impetus.eth.parser.EthQueryExecutor.getFromTable(EthQueryExecutor.java:156)
	at com.impetus.eth.parser.EthQueryExecutor.executeQuery(EthQueryExecutor.java:90)
	at com.impetus.eth.jdbc.EthStatement.executeQuery(EthStatement.java:309)
	at com.impetus.blkchn.eth.Query.main(Query.java:39)`

**Comment by ashishkshukla** [comment]
fixed with latest pull #27
